spring:
  port: 8085
  application:
    name: lpp
  #datasource:
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  #  url: jdbc:mysql://localhost:3306/lpp-dev?allowMultiQueries=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  #  username: root
  #  password: 414515
  #  max-idle: 10
  #  max-wait: 10000
  #  initial-size: 5
  #  profiles:
  #    active: true
#eureka server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
