cluster:
    datasource:
        initial-size: 5
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        password: 414515
        url: jdbc:mysql://localhost:3306/lpp-uat?allowMultiQueries=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8085/eureka
    instance:
        hostname: localhost
    server:
        enable-self-perservation: false
management:
    endpoint:
        health:
            show-details: always
        shutdown:
            enabled: true
    endpoints:
        web:
            base-path: /actuator
            exposure: 'include: "*"'
            exposure.include: health,info
    server:
        port: 8082
master:
    datasource:
        initial-size: 5
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        password: 414515
        url: jdbc:mysql://localhost:3306/lpp-dev?allowMultiQueries=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
server:
    port: 8082
spring:
    application:
        name: lpp-mybatis-learning
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat,wall,slf4j
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
