eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8085/eureka
management:
    endpoints:
        web:
            base-path: /manage
server:
    port: 8084
spring:
    application:
        name: lpp-cache
