server:
    port: 8081
spring:
    application:
        name: lpp-common
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat,wall,slf4j
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8085/eureka
master:
    datasource:
        initial-size: 5
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        password: 414515
        url: jdbc:mysql://localhost:3306/lpp-dev?allowMultiQueries=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root

